name: Whole Food Plant Based Life
description: Information and inspiration for a whole food plant based diet.
url: http://wfpblife.com
permalink: /blog/:year/:month/:day/:title
exclude:
- README.md
- upload
- assets
