name: Whole Food Plant Based Life
description: Information and inspiration for a whole food plant based diet.
url: http://wfpblife.com
auto: false
permalink: /blog/:year/:month/:day/:title
pygments: true
server: false
exclude:
- README.md
- upload
- assets
